export const departments = [
    { name: '政治経済学部', abbr: '政経' },
    { name: '法学部', abbr: '法学' },
    { name: '教育学部', abbr: '教育' },
    { name: '商学部', abbr: '商学' },
    { name: '社会科学部', abbr: '社学' },
    { name: '人間科学部', abbr: '人科' },
    { name: 'スポーツ科学部', abbr: 'スポーツ' },
    { name: '国際教養学部', abbr: '国際教養' },
    { name: '文化構想学部', abbr: '文構' },
    { name: '文学部', abbr: '文' },
    { name: '人間科学部（通信教育課程）', abbr: '人通' },
    { name: '基幹理工学部', abbr: '基幹' },
    { name: '創造理工学部', abbr: '創造' },
    { name: '先進理工学部', abbr: '先進' },
    { name: '政治学研究科', abbr: '政研' },
    { name: '経済学研究科', abbr: '経研' },
    { name: '法学研究科', abbr: '法研' },
    { name: '文学研究科', abbr: '文研' },
    { name: '商学研究科', abbr: '商研' },
    { name: '教育学研究科', abbr: '教研' },
    { name: '人間科学研究科', abbr: '人研' },
    { name: '社会科学研究科', abbr: '社学研' },
    { name: 'アジア太平洋研究科', abbr: 'アジア研' },
    { name: '日本語教育研究科', abbr: '日研' },
    { name: '情報生産システム研究科', abbr: '情シス研' },
    { name: '法務研究科', abbr: '法務研' },
    { name: '会計研究科', abbr: '会計研' },
    { name: 'スポーツ科学研究科', abbr: 'スポーツ研' },
    { name: '基幹理工学研究科', abbr: '基幹研' },
    { name: '創造理工学研究科', abbr: '創造研' },
    { name: '先進理工学研究科', abbr: '先進研' },
    { name: '環境・エネルギー研究科', abbr: '環エネ研' },
    { name: '国際コミュニケーション研究科', abbr: '国際コミ研' },
    { name: '経営管理研究科', abbr: '経管研' },
]

// @ts-ignore-next-line
enum Department {
    PSE = '政治経済学部',
    LAW = '法学部',
    CMS = '文化構想学部',
    HSS = '文学部',
    EDU = '教育学部',
    SOC = '商学部',
    FSE = '基幹理工学部',
    CSE = '創造理工学部',
    ASE = '先進理工学部',
    SSS = '社会科学部',
    HUM = '人間科学部',
    SPS = 'スポーツ科学部',
    SILS = '国際教養学部',
    HUME = '人間科学部（通信教育課程）',
    GSPS = '政治学研究科',
    GSE = '経済学研究科',
    LAWG = '法学研究科',
    LAS = '文学研究科',
    EDUG = '教育学研究科',
    GSC = '商学研究科',
    FSEG = '基幹理工学研究科',
    CSEG = '創造理工学研究科',
    ASEG = '先進理工学研究科',
    WEEE = '環境・エネルギー研究科',
    IPS = '情報生産システム研究科',
    GSSS = '社会科学研究科',
    HUMG = '人間科学研究科',
    SPSG = 'スポーツ科学研究科',
    GSICCS = '国際コミュニケーション研究科',
    GSAPS = 'アジア太平洋研究科',
    GSJAL = '日本語教育研究科',
}
